// ********RoostGPT********
/*
Test generated by RoostGPT for test demoTestGitlab using AI Type Open AI and AI Model gpt-4

Here are some test scenarios to validate the business logic of the `getBtnEqualTextColor` function:

1. **Scenario:** Verify that the method returns a string
   - **Given:** N/A
   - **When:** `getBtnEqualTextColor` function is called
   - **Then:** Validate that the returned value is a string

2. **Scenario:** Verify that the method returns the expected color
   - **Given:** The `btnEqualTextColor` is set to a specific color (e.g. "red")
   - **When:** `getBtnEqualTextColor` function is called
   - **Then:** Validate that the returned color is the same as the set color

3. **Scenario:** Verify that the method returns null if the `btnEqualTextColor` has not been set
   - **Given:** The `btnEqualTextColor` has not been set
   - **When:** `getBtnEqualTextColor` function is called
   - **Then:** Validate that the returned value is null

4. **Scenario:** Verify that the method returns the correct color after the `btnEqualTextColor` has been changed
   - **Given:** The `btnEqualTextColor` is set to a specific color (e.g. "red")
   - **And:** The `btnEqualTextColor` is then changed to a different color (e.g. "blue")
   - **When:** `getBtnEqualTextColor` function is called
   - **Then:** Validate that the returned color is the new set color (e.g. "blue")

5. **Scenario:** Verify that the method returns the correct color when called multiple times without changing the `btnEqualTextColor`
   - **Given:** The `btnEqualTextColor` is set to a specific color (e.g. "red")
   - **When:** `getBtnEqualTextColor` function is called multiple times
   - **Then:** Validate that the returned color is the same each time

Remember, these are only scenarios. The actual implementation of these tests will depend on the testing framework you are using.
*/

// ********RoostGPT********
package com.houarizegai.calculator.theme.properties;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class Theme_getBtnEqualTextColor_0af88d5c28_Test {
    private Theme theme;

    @BeforeEach
    public void setUp() {
        theme = new Theme();
    }

    @Test
    public void testGetBtnEqualTextColor_ReturnsString() {
        theme.setBtnEqualTextColor("red");
        assertTrue(theme.getBtnEqualTextColor() instanceof String);
    }

    @Test
    public void testGetBtnEqualTextColor_ReturnsExpectedColor() {
        theme.setBtnEqualTextColor("red");
        assertEquals("red", theme.getBtnEqualTextColor());
    }

    @Test
    public void testGetBtnEqualTextColor_ReturnsNullIfNotSet() {
        assertNull(theme.getBtnEqualTextColor());
    }

    @Test
    public void testGetBtnEqualTextColor_ReturnsCorrectColorAfterChange() {
        theme.setBtnEqualTextColor("red");
        theme.setBtnEqualTextColor("blue");
        assertEquals("blue", theme.getBtnEqualTextColor());
    }

    @Test
    public void testGetBtnEqualTextColor_ReturnsSameColorWhenCalledMultipleTimesWithoutChange() {
        theme.setBtnEqualTextColor("red");
        assertEquals("red", theme.getBtnEqualTextColor());
        assertEquals("red", theme.getBtnEqualTextColor());
    }
}
