// ********RoostGPT********
/*
Test generated by RoostGPT for test demoTestGitlab using AI Type Open AI and AI Model gpt-4

1. Scenario: Check if the function getThemes returns a non-null list of themes.
   Test Case: Call the getThemes function and check if the returned list is not null.

2. Scenario: Check if the function getThemes returns an empty list when there are no themes.
   Test Case: Call the getThemes function when no themes are added and check if the returned list is empty.

3. Scenario: Check if the function getThemes returns a list containing all the themes.
   Test Case: Add several themes, call the getThemes function and check if all the added themes are present in the returned list.

4. Scenario: Check if the function getThemes returns a list with the same order of themes as they were added.
   Test Case: Add several themes in a specific order, call the getThemes function and check if the themes in the returned list are in the same order as they were added.

5. Scenario: Check if the function getThemes returns a list with the correct number of themes.
   Test Case: Add several themes, call the getThemes function and check if the number of themes in the returned list is equal to the number of themes added.

6. Scenario: Check if the function getThemes maintains the immutability of the themes.
   Test Case: Call the getThemes function, modify the returned list and check if the original list of themes is not affected.

7. Scenario: Check if the function getThemes returns a list of unique themes.
   Test Case: Add duplicate themes, call the getThemes function and check if the returned list contains no duplicate themes.

8. Scenario: Check if the function getThemes returns a list of themes without any null values.
   Test Case: Add a null theme, call the getThemes function and check if the returned list does not contain the null theme.

9. Scenario: Check if the function getThemes does not modify the original list of themes.
   Test Case: Call the getThemes function, modify the returned list and check if the original list of themes remains the same.

10. Scenario: Check if the function getThemes returns a list of themes that are instances of the Theme class.
    Test Case: Call the getThemes function and check if all the items in the returned list are instances of the Theme class.
*/

// ********RoostGPT********
package com.houarizegai.calculator.theme.properties;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class ThemeList_getThemes_1ad0f9f985_Test {

    private ThemeList themeList;
    private Theme theme1;
    private Theme theme2;

    @BeforeEach
    public void setUp() {
        themeList = new ThemeList();
        theme1 = new Theme();
        theme2 = new Theme();
    }

    @Test
    public void testGetThemesWhenListIsNull() {
        assertNull(themeList.getThemes(), "Expected null when no themes are added.");
    }

    @Test
    public void testGetThemesWhenListIsEmpty() {
        themeList.setThemes(new ArrayList<>());
        assertTrue(themeList.getThemes().isEmpty(), "Expected empty list when no themes are added.");
    }

    @Test
    public void testGetThemesWhenThemesAreAdded() {
        List<Theme> themes = new ArrayList<>();
        themes.add(theme1);
        themes.add(theme2);

        themeList.setThemes(themes);

        List<Theme> retrievedThemes = themeList.getThemes();
        assertEquals(2, retrievedThemes.size(), "Expected the list to have 2 themes.");
        assertEquals(theme1, retrievedThemes.get(0), "Expected the first theme to be theme1.");
        assertEquals(theme2, retrievedThemes.get(1), "Expected the second theme to be theme2.");
    }

    @Test
    public void testGetThemesImmutability() {
        List<Theme> themes = new ArrayList<>();
        themes.add(theme1);

        themeList.setThemes(themes);

        List<Theme> retrievedThemes = new ArrayList<>(themeList.getThemes());
        retrievedThemes.add(theme2);

        assertEquals(1, themeList.getThemes().size(), "Expected the original list not to be affected by changes to the retrieved list.");
    }
}
