// ********RoostGPT********
/*
Test generated by RoostGPT for test demoTestGitlab using AI Type Open AI and AI Model gpt-4

1. Scenario: Test when a valid color code is passed as `btnEqualBackground`.
   - Given the color code "#FFFFFF" as `btnEqualBackground`.
   - When `setBtnEqualBackground` is called.
   - Then confirm that the `btnEqualBackground` is set to "#FFFFFF".

2. Scenario: Test when an invalid color code is passed as `btnEqualBackground`.
   - Given the color code "#ZZZZZZ" as `btnEqualBackground`.
   - When `setBtnEqualBackground` is called.
   - Then confirm that an appropriate error or exception is thrown.

3. Scenario: Test when `btnEqualBackground` is set to null.
   - Given null as `btnEqualBackground`.
   - When `setBtnEqualBackground` is called.
   - Then confirm that an appropriate error or exception is thrown.

4. Scenario: Test when `btnEqualBackground` is set to an empty string.
   - Given an empty string as `btnEqualBackground`.
   - When `setBtnEqualBackground` is called.
   - Then confirm that an appropriate error or exception is thrown.

5. Scenario: Test when a valid color name is passed as `btnEqualBackground`.
   - Given "blue" as `btnEqualBackground`.
   - When `setBtnEqualBackground` is called.
   - Then confirm that the `btnEqualBackground` is set to "blue".

6. Scenario: Test when an invalid color name is passed as `btnEqualBackground`.
   - Given "invalidcolor" as `btnEqualBackground`.
   - When `setBtnEqualBackground` is called.
   - Then confirm that an appropriate error or exception is thrown.

7. Scenario: Test when a valid color code without the '#' symbol is passed as `btnEqualBackground`.
   - Given "FFFFFF" as `btnEqualBackground`.
   - When `setBtnEqualBackground` is called.
   - Then confirm that the `btnEqualBackground` is set to "FFFFFF".

8. Scenario: Test when a valid color code with additional characters is passed as `btnEqualBackground`.
   - Given "#FFFFFFextra" as `btnEqualBackground`.
   - When `setBtnEqualBackground` is called.
   - Then confirm that an appropriate error or exception is thrown.

Please note that these scenarios are assuming that the `btnEqualBackground` is expected to be a color code or color name. If the business logic of your application defines `btnEqualBackground` differently, these scenarios may need to be adjusted.
*/

// ********RoostGPT********
package com.houarizegai.calculator.theme.properties;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class Theme_setBtnEqualBackground_85fbd39ea7_Test {

    @Test
    public void testSetBtnEqualBackground_ValidColorCode() {
        Theme theme = new Theme();
        theme.setBtnEqualBackground("#FFFFFF");
        assertEquals("#FFFFFF", theme.getBtnEqualBackground());
    }

    @Test
    public void testSetBtnEqualBackground_InvalidColorCode() {
        Theme theme = new Theme();
        assertThrows(IllegalArgumentException.class, () -> theme.setBtnEqualBackground("#ZZZZZZ"));
    }

    @Test
    public void testSetBtnEqualBackground_Null() {
        Theme theme = new Theme();
        assertThrows(NullPointerException.class, () -> theme.setBtnEqualBackground(null));
    }

    @Test
    public void testSetBtnEqualBackground_EmptyString() {
        Theme theme = new Theme();
        assertThrows(IllegalArgumentException.class, () -> theme.setBtnEqualBackground(""));
    }

    @Test
    public void testSetBtnEqualBackground_ValidColorName() {
        Theme theme = new Theme();
        theme.setBtnEqualBackground("blue");
        assertEquals("blue", theme.getBtnEqualBackground());
    }

    @Test
    public void testSetBtnEqualBackground_InvalidColorName() {
        Theme theme = new Theme();
        assertThrows(IllegalArgumentException.class, () -> theme.setBtnEqualBackground("invalidcolor"));
    }

    @Test
    public void testSetBtnEqualBackground_ValidColorCodeWithoutHash() {
        Theme theme = new Theme();
        theme.setBtnEqualBackground("FFFFFF");
        assertEquals("FFFFFF", theme.getBtnEqualBackground());
    }

    @Test
    public void testSetBtnEqualBackground_ValidColorCodeWithExtraCharacters() {
        Theme theme = new Theme();
        assertThrows(IllegalArgumentException.class, () -> theme.setBtnEqualBackground("#FFFFFFextra"));
    }
}
