// ********RoostGPT********
/*
Test generated by RoostGPT for test demoTestGitlab using AI Type Open AI and AI Model gpt-4

Test generated for /apikeys_get for http method type GET in rest-assured framework

RoostTestHash=9e57a3b0dd


*/

// ********RoostGPT********
package com.houari.RoostTest;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import org.junit.Before;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import org.hamcrest.MatcherAssert;
import java.util.Map;
import java.util.List;
import java.util.ArrayList;

public class apikeysGetTest {

    private List<Map<String, String>> envList = new ArrayList<>();

    @Before
    public void setUp() {
        TestdataLoader dataloader = new TestdataLoader();
        envList = dataloader.loadData("src/test/java/com/houari/RoostTest/apikeysGetTest.csv");
    }

    @Test  
    public void apikeysGet_Test() {
        setUp();
        for (Map<String, String> map : envList) {
            RestAssured.baseURI = map.get("BASE_URL");  

            Response response = given()
				.header("Token", map.get("API_KEY"))
                .when()
                .get("/apikeys")  
                .then() 
                .extract().response();    

            switch (response.statusCode()) {
                case 200:
                    validateSuccessfulResponse(response);
                    break;
                case 400:
                    validateErrorResponse(response);
                    break;
                case 401:
                    validateAuthenticationRequiredResponse(response);
                    break;
                default:
                    System.out.println("Unexpected status code: " + response.statusCode());
            }
        }  
    }

    private void validateSuccessfulResponse(Response response) {
        System.out.println("Description: successful operation");
        MatcherAssert.assertThat(response.jsonPath().get("total"), instanceOf(Integer.class));
        MatcherAssert.assertThat(response.jsonPath().getList("apikeys"), instanceOf(List.class));
    }

    private void validateErrorResponse(Response response) {
        System.out.println("Description: Bad Request");
        MatcherAssert.assertThat(response.jsonPath().get("error"), instanceOf(String.class));
        MatcherAssert.assertThat(response.jsonPath().get("description"), instanceOf(String.class));
        MatcherAssert.assertThat(response.jsonPath().getString("error"), matchesPattern("^validation/.*$"));
        MatcherAssert.assertThat(response.jsonPath().get("field"), instanceOf(String.class));
        MatcherAssert.assertThat(response.jsonPath().get("schema_field"), instanceOf(String.class));
    }

    private void validateAuthenticationRequiredResponse(Response response) {
        System.out.println("Description: Authentication Required");
        MatcherAssert.assertThat(response.jsonPath().get("error"), instanceOf(String.class));
        MatcherAssert.assertThat(response.jsonPath().get("description"), instanceOf(String.class));
        MatcherAssert.assertThat(response.jsonPath().getString("error"), matchesPattern("^validation/.*$"));
        MatcherAssert.assertThat(response.jsonPath().get("field"), instanceOf(String.class));
        MatcherAssert.assertThat(response.jsonPath().get("schema_field"), instanceOf(String.class));
    }
}
