// ********RoostGPT********
/*
Test generated by RoostGPT for test advancedReportTest using AI Type  and AI Model 

ROOST_METHOD_HASH=6fd420fbbc
ROOST_METHOD_SIG_HASH=dcb7881d11

 ########## Scenario ########## 

{
  feature: 'Feature: Test API from Alphavantage.co',
  background: null,
  rule: null,
  scenario: {
    title: 'Scenario: Attempt to retrieve data without an API key',
    steps: 'Given the Alpha Vantage API endpoint is "https://www.alphavantage.co/query"\n' +
      'When I send a GET request with the following parameters:\n' +
      '      | Parameter | Value             |\n' +
      '      | function  | TIME_SERIES_DAILY |\n' +
      '      | symbol    | AAPL              |\n' +
      'Then the response should indicate an error for missing API key',
    examples: ''
  }
}

*/

// ********RoostGPT********
package com.houari.RoostTest;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.containsString;

public class AttemptToRetrieveDataWithoutAPIKeyTest {

    private static final String BASE_URL = "https://www.alphavantage.co/query";

    @BeforeAll
    public static void setup() {
        RestAssured.baseURI = BASE_URL;
    }

    @Test
    public void testRetrieveDataWithoutAPIKey() {
        Response response = given()
            .param("function", "TIME_SERIES_DAILY")
            .param("symbol", "AAPL")
        .when()
            .get()
        .then()
            .extract().response();

        // Assert that the response indicates an error for missing API key
        response.then().statusCode(400); // Assuming 400 Bad Request is returned for missing API key
        response.then().body(containsString("Error")); // Assuming the response body contains "Error" message
        response.then().body(containsString("API key")); // Assuming the response mentions "API key"
    }
}
