# ********RoostGPT********

# Test generated by RoostGPT for test java-customannotation-test using AI Type  and AI Model 
# 
# ROOST_METHOD_HASH=f53f0e46c1
# ROOST_METHOD_SIG_HASH=bd730d3207
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Work Order Management API',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: Delete an existing work order',
#     steps: 'Given the API endpoint is "/workorders/{id}"\n' +
#       'And the work order ID is "WO123"\n' +
#       'When I send a DELETE request to delete the work order\n' +
#       'Then the response status code should be 204',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Work Order Management API

  Background:
    * url 'http://example.com/api'

  Scenario: Delete an existing work order with valid ID
    Given path '/workorders/WO123'
    When method delete
    Then status 204

  Scenario: Delete an existing work order with invalid ID
    Given path '/workorders/invalidID123'
    When method delete
    Then status 404
