# ********RoostGPT********

# Test generated by RoostGPT for test java-customannotation-test using AI Type  and AI Model 
# 
# Feature file generated for /kafka/v3/clusters/{cluster_id}/topics_get for http method type GET 
# RoostTestHash=5a89adf6e3
# 
# 

# ********RoostGPT********
Feature: List Topics in Kafka Cluster

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: GET request to list all topics in a kafka cluster
    Given path 'kafka/v3/clusters/', <cluster_id>, '/topics'
    And header Authorization = 'Bearer ' + karate.properties['AUTH_TOKEN']
    When method get
    Then status 200
    And match response.kind == 'KafkaTopicList'
    And match response.metadata.self == '#string'
    And match response.data[0].kind == 'KafkaTopic'
    And match each response.data contains { cluster_id: '#string', topic_name: '#string', is_internal: '#boolean' }

    Examples:
      | read('kafka_v3_clusters_cluster_id_topics_get.csv') |

  Scenario: GET request for non-existing cluster to ensure proper error handling
    Given path 'kafka/v3/clusters/', 'non-existing-cluster', '/topics'
    And header Authorization = 'Bearer ' + karate.properties['AUTH_TOKEN']
    When method get
    Then status 404
    And match response.error == 'Cluster not found'

  Scenario Outline: Rate limit error handling by sending too high a request frequency
    Given path 'kafka/v3/clusters/', <cluster_id>, '/topics'
    And header Authorization = 'Bearer ' + karate.properties['AUTH_TOKEN']
    When method get
    Then status 429
    And match response.message == 'Too Many Requests'

    Examples:
      | cluster_id  |
      | 'cluster-1' |
      | 'cluster-2' |

  Scenario Outline: Verify correct error messages are returned when unauthorized
    Given path 'kafka/v3/clusters/', <cluster_id>, '/topics'
    And header Authorization = 'InvalidToken'
    When method get
    Then status 401
    And match response.error_code == 40101
    And match response.message == 'Authentication failed'

    Examples:
      | cluster_id  |
      | 'cluster-1' |
      | 'cluster-2' |
