# ********RoostGPT********

# Test generated by RoostGPT for test java-customannotation-test using AI Type  and AI Model 
# 
# Feature file generated for /kafka/v3/clusters/{cluster_id}/topics_post for http method type POST 
# RoostTestHash=783e9d2ab5
# 
# 

# ********RoostGPT********
Feature: Topic Creation for Kafka Cluster

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Create a new Kafka topic with different configurations
    Given path '/kafka/v3/clusters/', <cluster_id>, '/topics'
    And request
      """
      <request_body>
      """
    And header Authorization = 'Bearer ' + karate.properties['AUTH_TOKEN']
    When method post
    Then status <expected_status>
    And match response ==
      """
      <expected_response>
      """

    Examples:
      | read('kafka_v3_clusters_cluster_id_topics_post.csv') |
