# ********RoostGPT********

# Test generated by RoostGPT for test java-customannotation-test using AI Type  and AI Model 
# 
# Feature file generated for /kafka/v3/clusters/{cluster_id}/topics/{topic_name}_patch for http method type PATCH 
# RoostTestHash=9d07b67b96
# 
# 

# ********RoostGPT********
Feature: Update Partition Count for Kafka Topic

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * header Authorization = 'Bearer ' + authToken

  Scenario Outline: Successfully increase the number of partitions for a topic
    Given path 'kafka/v3/clusters/', <cluster_id>, '/topics/', <topic_name>
    And request { "partitions_count": <partitions_count> }
    When method patch
    Then status 200
    And match response contains { "kind": "KafkaTopic" }

    Examples:
      | read('kafka_v3_clusters_cluster_id_topics_topic_name_patch.csv') |

  Scenario Outline: Fail to update partitions due to bad request format
    Given path 'kafka/v3/clusters/', <cluster_id>, '/topics/', <topic_name>
    And request { "partitions_count": <partitions_count> }
    When method patch
    Then status 400
    And match response contains { "status": "400", "code": "InvalidFormat", "title": "Bad Request" }

    Examples:
      | cluster_id  | topic_name | partitions_count |
      | "cluster-1" | "topic-1"  | "invalid_count"  |
      | "cluster-1" | "topic-1"  |               -1 |

  Scenario Outline: Unauthorized attempt to update partitions
    Given path 'kafka/v3/clusters/', <cluster_id>, '/topics/', <topic_name>
    And header Authorization = 'Bearer ' + (karate.properties['badAuthToken'] || 'InvalidToken')
    And request { "partitions_count": <partitions_count> }
    When method patch
    Then status 401
    And match response contains { "error_code": 40101, "message": "Authentication failed" }

    Examples:
      | cluster_id  | topic_name | partitions_count |
      | "cluster-1" | "topic-1"  |                2 |

  Scenario Outline: Forbidden access attempt to update partitions
    Given path 'kafka/v3/clusters/', <cluster_id>, '/topics/', <topic_name>
    And header Authorization = 'Bearer ' + (karate.properties['badAuthToken'] || 'InvalidToken')
    And request { "partitions_count": <partitions_count> }
    When method patch
    Then status 403
    And match response contains { "error_code": 40301, "message": "Request is not authorized" }

    Examples:
      | cluster_id  | topic_name | partitions_count |
      | "cluster-1" | "topic-1"  |                2 |
