# ********RoostGPT********

# Test generated by RoostGPT for test java-customannotation-test using AI Type  and AI Model 
# 
# ROOST_METHOD_HASH=82a3ebe016
# ROOST_METHOD_SIG_HASH=387615e444
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Work Order Management API',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: Retrieve work orders by assigned user',
#     steps: 'Given the API endpoint is "/workorders?assignedTo=John Doe"\n' +
#       'When I send a GET request to retrieve work orders assigned to "John Doe"\n' +
#       'Then the response status code should be 200\n' +
#       'And the response should contain a list of work orders assigned to "John Doe"',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Work Order Management API

  Background:
    * url 'http://example.com/api'

  Scenario: Retrieve work orders by assigned user
    Given path '/workorders?assignedTo=John Doe'
    When method get
    Then status 200
    And match response contains 'John Doe'
