# ********RoostGPT********

# Test generated by RoostGPT for test test-workflow using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# ROOST_METHOD_HASH=61d4e70ce5
# ROOST_METHOD_SIG_HASH=22194d4874
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Test API from Alphavantage.co',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: Attempt to retrieve data with an invalid API key',
#     steps: 'Given the API endpoint is "https://www.alphavantage.co/query"\n' +
#       'When I send a GET request with the following parameters:\n' +
#       '      | Parameter | Value                     |\n' +
#       '      | function  | TIME_SERIES_DAILY_ADJUSTED |\n' +
#       '      | symbol    | IBM                       |\n' +
#       '      | apikey    | invalid_key               |\n' +
#       'Then the response should indicate an authentication error',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Test API from Alphavantage.co

Background:
  * def alphavantage-get-resolved_URL = karate.properties['alphavantage-get-resolved_URL'] || karate.get('alphavantage-get-resolved_URL', 'http://localhost:4010')
  * url alphavantage-get-resolved_URL

Scenario: Attempt to retrieve data with an invalid API key
  Given path '/query'
  And params 
  """
  { 
  "function": "TIME_SERIES_DAILY_ADJUSTED", 
  "symbol": "IBM", 
  "apikey": "invalid_key" 
  }
  """
  When method get
  Then status 200
  And match response == { Information: 'Invalid API call. Please retry or finally check your api key values.' }
