# ********RoostGPT********

# Test generated by RoostGPT for test test-workflow using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# ROOST_METHOD_HASH=0a60f0444c
# ROOST_METHOD_SIG_HASH=736ee1b30e
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Test API from Alphavantage.co',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: Get Basic Financials',
#     steps: 'Given the Finnhub API base URL is "https://finnhub.io/api/v1"\n' +
#       'When I send a GET request to "/stock/metric?symbol=AAPL&metric=all"\n' +
#       'Then the response status code should be 200\n' +
#       'And the response should contain financial metrics',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Test API from Alphavantage.co

Background:
  # Setting up the API HOST
  * def FINNHUB_URL = karate.properties['FINNHUB_URL'] || 'http://localhost:4010'
  * url FINNHUB_URL

  # Setting up the AUTH TOKEN (if and only if required)
  * def finnhub_AUTH_TOKEN = karate.properties['FINNHUB_AUTH_TOKEN']
  * header Authorization = finnhub_AUTH_TOKEN


Scenario: Get Basic Financials
  # Given the API endpoint
  Given path '/stock/metric?symbol=AAPL&metric=all'
  # When a GET request is made
  When method get
  # Then the response status code should be 200
  Then status 200
  # And the response body should contain financial metrics
  And match response == { symbol: '#string', metricType: '#string', series: '#notnull', metric: '#notnull'}
