# ********RoostGPT********

# Test generated by RoostGPT for test test-workflow using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# ROOST_METHOD_HASH=1749883a0e
# ROOST_METHOD_SIG_HASH=b021e62269
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Test API from Alphavantage.co',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: Get Recommendation Trends',
#     steps: 'Given the Finnhub API base URL is "https://finnhub.io/api/v1"\n' +
#       'When I send a GET request to "/stock/recommendation?symbol=AAPL"\n' +
#       'Then the response status code should be 200\n' +
#       'And the response should contain recommendation trends',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Test API from Alphavantage.co

  Background:
    * def FINNHUB_URL = karate.properties['FINNHUB_URL'] || 'http://localhost:4010'
    * url FINNHUB_URL
    * def FINNHUB_AUTH_TOKEN = karate.properties['FINNHUB_AUTH_TOKEN']
    * header Authorization = FINNHUB_AUTH_TOKEN

  Scenario: Get Recommendation Trends
    Given path '/stock/recommendation?symbol=AAPL'
    When method get
    Then status 200
    And match each response contains 
    """
    { symbol: '#string', 
      buy: '#number', 
      hold: '#number', 
      period: '#string', 
      sell: '#number', 
      strongBuy: '#number', 
      strongSell: '#number' }
    """
