# ********RoostGPT********

# Test generated by RoostGPT for test test-workflow using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# ROOST_METHOD_HASH=4cfe99b3e5
# ROOST_METHOD_SIG_HASH=05511af534
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Alpha Vantage Daily Time Series API',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: Attempt to retrieve data with an invalid symbol',
#     steps: 'Given the Alpha Vantage API endpoint is "https://www.alphavantage.co/query"\n' +
#       'When I send a GET request with the following parameters:\n' +
#       '      | Parameter | Value             |\n' +
#       '      | function  | TIME_SERIES_DAILY |\n' +
#       '      | symbol    | INVALID_SYMBOL    |\n' +
#       '      | apikey    | demo              |\n' +
#       'Then the response should indicate an error for invalid symbol',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Alpha Vantage Daily Time Series API

Background: 
  * def ALPHAVANTAGE_GET_RESOLVED_URL = karate.properties['ALPHAVANTAGE_GET_RESOLVED_URL'] || karate.get('ALPHAVANTAGE_GET_RESOLVED_URL', 'http://localhost:4010')

Scenario Outline: Attempt to retrieve data with an invalid symbol
    Given url ALPHAVANTAGE_GET_RESOLVED_URL
    And path '/query'
    And params
      | parameter | value             |
      | function  | TIME_SERIES_DAILY |
      | symbol    | INVALID_SYMBOL    |
      | apikey    | demo              |

    When method get
    Then status 200
    And match response contains 'Error Message'
