# ********RoostGPT********

# Test generated by RoostGPT for test advancedReportTest using AI Type  and AI Model 
# 
# ROOST_METHOD_HASH=e027123530
# ROOST_METHOD_SIG_HASH=24c692fb0c
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Test API from Alphavantage.co',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: Verify time series order',
#     steps: 'Given I have retrieved the daily time series data for AAPL stock\n' +
#       'Then the dates should be in descending order\n' +
#       'And the most recent date should not be in the future',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Test API from Alphavantage.co

Scenario: Verify time series order
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
  * url urlBase

  Given path '/query'
  And param symbol = 'AAPL'
  And param apikey = 'demo'
  And param function = 'TIME_SERIES_DAILY_ADJUSTED'
  When method GET
  Then status 200

  * def timeSeriesData = response['Time Series (Daily)']
  * def dates = Object.keys(timeSeriesData)
  * assert dates.length > 1

  * def isDescending = function(arr) { 
      for (var i = 1; i < arr.length; i++) 
        if (arr[i] > arr[i-1]) return false; 
      return true; 
    }
  * assert isDescending(dates) == true

  * def mostRecentDate = dates[0]
  * def today = new Date().toISOString().split('T')[0]
  * assert mostRecentDate <= today
