# ********RoostGPT********

# Test generated by RoostGPT for test advancedReportTest using AI Type  and AI Model 
# 
# ROOST_METHOD_HASH=7f27d0f027
# ROOST_METHOD_SIG_HASH=d5853d6df0
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Test API from Alphavantage.co',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: Verify specific date data in time series',
#     steps: 'Given I have retrieved the daily time series data for AAPL stock\n' +
#       'When I check the data for "2024-07-09"\n' +
#       'Then it should have the following values:\n' +
#       '      | Field     | Value     |\n' +
#       '      | 1. open   | 227.9300  |\n' +
#       '      | 2. high   | 229.4000  |\n' +
#       '      | 3. low    | 226.3721  |\n' +
#       '      | 4. close  | 228.6800  |\n' +
#       '      | 5. volume | 48169822  |',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Test API from Alphavantage.co

  Scenario: Verify specific date data in time series
    * url karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    And path '/query'
    And param symbol = 'AAPL'
    And param function = 'TIME_SERIES_DAILY_ADJUSTED'
    And param apikey = 'demo'
    When method GET
    Then status 200
    And def responseJson = response
    And def specificDate = '2024-07-09'
    And def dateData = responseJson['Time Series (Daily)'][specificDate]
    Then match dateData['1. open'] == '227.9300'
    And match dateData['2. high'] == '229.4000'
    And match dateData['3. low'] == '226.3721'
    And match dateData['4. close'] == '228.6800'
    And match dateData['5. volume'] == '48169822'
    And match response contains { 'Meta Data': '#object' }
    And match response contains { 'Time Series (Daily)': '#object' }
    And match response['Meta Data'] contains { '1. Information': '#string' }
    And match response['Meta Data'] contains { '2. Symbol': 'AAPL' }
    And match response['Meta Data'] contains { '3. Last Refreshed': '#string' }
    And match response['Meta Data'] contains { '4. Output Size': '#string' }
    And match response['Meta Data'] contains { '5. Time Zone': '#string' }
